// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/annotations.proto

#include "proto/stu3/annotations.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace google {
namespace fhir {
namespace stu3 {
namespace proto {
}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace protobuf_proto_2fstu3_2fannotations_2eproto {
void InitDefaults() {
}

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "proto/stu3/annotations.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\034proto/stu3/annotations.proto\022\026google.f"
      "hir.stu3.proto\032 google/protobuf/descript"
      "or.proto*\205\001\n\034StructureDefinitionKindValu"
      "e\022\020\n\014KIND_UNKNOWN\020\000\022\027\n\023KIND_PRIMITIVE_TY"
      "PE\020\001\022\025\n\021KIND_COMPLEX_TYPE\020\002\022\021\n\rKIND_RESO"
      "URCE\020\003\022\020\n\014KIND_LOGICAL\020\004*5\n\013Requirement\022"
      "\020\n\014NOT_REQUIRED\020\000\022\024\n\020REQUIRED_BY_FHIR\020\001:"
      "=\n\021fhir_valueset_url\022\037.google.protobuf.M"
      "essageOptions\030\221\277\240V \001(\t:\?\n\023fhir_reference"
      "_type\022\037.google.protobuf.MessageOptions\030\221"
      "\344\302W \003(\t:{\n\031structure_definition_kind\022\037.g"
      "oogle.protobuf.MessageOptions\030\370\263\354V \001(\01624"
      ".google.fhir.stu3.proto.StructureDefinit"
      "ionKindValue:\?\n\023message_description\022\037.go"
      "ogle.protobuf.MessageOptions\030\324\206\357Z \001(\t:7\n"
      "\013value_regex\022\037.google.protobuf.MessageOp"
      "tions\030\242\257\304a \001(\t:I\n\035fhir_structure_definit"
      "ion_url\022\037.google.protobuf.MessageOptions"
      "\030\346\317\374b \001(\t:=\n\021fhir_profile_base\022\037.google."
      "protobuf.MessageOptions\030\323\346\261b \001(\t:B\n\022fhir"
      "_extension_url\022\037.google.protobuf.Message"
      "Options\030\305\231\266T \001(\tB\002\030\001:@\n\022fhir_original_co"
      "de\022!.google.protobuf.EnumValueOptions\030\347\262"
      "\247V \001(\t:e\n\026validation_requirement\022\035.googl"
      "e.protobuf.FieldOptions\030\216\372\260M \001(\0162#.googl"
      "e.fhir.stu3.proto.Requirement:8\n\016is_choi"
      "ce_type\022\035.google.protobuf.FieldOptions\030\237"
      "\274\234Y \001(\010:;\n\021field_description\022\035.google.pr"
      "otobuf.FieldOptions\030\331\303\342Z \001(\t:7\n\rfhir_sli"
      "ce_by\022\035.google.protobuf.FieldOptions\030\324\315\202"
      "e \001(\t:7\n\rfhir_slice_of\022\035.google.protobuf"
      ".FieldOptions\030\374\353\201e \001(\t::\n\020fhir_slice_val"
      "ue\022\035.google.protobuf.FieldOptions\030\333\317\202e \001"
      "(\t:D\n\032fhir_inlined_extension_url\022\035.googl"
      "e.protobuf.FieldOptions\030\305\377\261b \001(\t:D\n\032fhir"
      "_inlined_coding_system\022\035.google.protobuf"
      ".FieldOptions\030\377\314\202e \001(\t:B\n\030fhir_inlined_c"
      "oding_code\022\035.google.protobuf.FieldOption"
      "s\030\304\367\222e \001(\t:>\n\024valid_reference_type\022\035.goo"
      "gle.protobuf.FieldOptions\030\376\317\257h \003(\t:@\n\026fh"
      "ir_oneof_is_optional\022\035.google.protobuf.O"
      "neofOptions\030\346\255\242f \001(\010B)\n\032com.google.fhir."
      "stu3.protoB\013Annotationsb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1711);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/stu3/annotations.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fstu3_2fannotations_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace proto {
const ::google::protobuf::EnumDescriptor* StructureDefinitionKindValue_descriptor() {
  protobuf_proto_2fstu3_2fannotations_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fstu3_2fannotations_2eproto::file_level_enum_descriptors[0];
}
bool StructureDefinitionKindValue_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Requirement_descriptor() {
  protobuf_proto_2fstu3_2fannotations_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fstu3_2fannotations_2eproto::file_level_enum_descriptors[1];
}
bool Requirement_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::std::string fhir_valueset_url_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_valueset_url(kFhirValuesetUrlFieldNumber, fhir_valueset_url_default);
const ::std::string fhir_reference_type_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  fhir_reference_type(kFhirReferenceTypeFieldNumber, fhir_reference_type_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::google::fhir::stu3::proto::StructureDefinitionKindValue, ::google::fhir::stu3::proto::StructureDefinitionKindValue_IsValid>, 14, false >
  structure_definition_kind(kStructureDefinitionKindFieldNumber, static_cast< ::google::fhir::stu3::proto::StructureDefinitionKindValue >(0));
const ::std::string message_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  message_description(kMessageDescriptionFieldNumber, message_description_default);
const ::std::string value_regex_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  value_regex(kValueRegexFieldNumber, value_regex_default);
const ::std::string fhir_structure_definition_url_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_structure_definition_url(kFhirStructureDefinitionUrlFieldNumber, fhir_structure_definition_url_default);
const ::std::string fhir_profile_base_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_profile_base(kFhirProfileBaseFieldNumber, fhir_profile_base_default);
const ::std::string fhir_extension_url_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_extension_url(kFhirExtensionUrlFieldNumber, fhir_extension_url_default);
const ::std::string fhir_original_code_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_original_code(kFhirOriginalCodeFieldNumber, fhir_original_code_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::google::fhir::stu3::proto::Requirement, ::google::fhir::stu3::proto::Requirement_IsValid>, 14, false >
  validation_requirement(kValidationRequirementFieldNumber, static_cast< ::google::fhir::stu3::proto::Requirement >(0));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  is_choice_type(kIsChoiceTypeFieldNumber, false);
const ::std::string field_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_description(kFieldDescriptionFieldNumber, field_description_default);
const ::std::string fhir_slice_by_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_by(kFhirSliceByFieldNumber, fhir_slice_by_default);
const ::std::string fhir_slice_of_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_of(kFhirSliceOfFieldNumber, fhir_slice_of_default);
const ::std::string fhir_slice_value_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_value(kFhirSliceValueFieldNumber, fhir_slice_value_default);
const ::std::string fhir_inlined_extension_url_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_extension_url(kFhirInlinedExtensionUrlFieldNumber, fhir_inlined_extension_url_default);
const ::std::string fhir_inlined_coding_system_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_coding_system(kFhirInlinedCodingSystemFieldNumber, fhir_inlined_coding_system_default);
const ::std::string fhir_inlined_coding_code_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_coding_code(kFhirInlinedCodingCodeFieldNumber, fhir_inlined_coding_code_default);
const ::std::string valid_reference_type_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  valid_reference_type(kValidReferenceTypeFieldNumber, valid_reference_type_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::OneofOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  fhir_oneof_is_optional(kFhirOneofIsOptionalFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
