// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/annotations.proto

#ifndef PROTOBUF_INCLUDED_proto_2fstu3_2fannotations_2eproto
#define PROTOBUF_INCLUDED_proto_2fstu3_2fannotations_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fannotations_2eproto 

namespace protobuf_proto_2fstu3_2fannotations_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_2fstu3_2fannotations_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace proto {
}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace google {
namespace fhir {
namespace stu3 {
namespace proto {

enum StructureDefinitionKindValue {
  KIND_UNKNOWN = 0,
  KIND_PRIMITIVE_TYPE = 1,
  KIND_COMPLEX_TYPE = 2,
  KIND_RESOURCE = 3,
  KIND_LOGICAL = 4,
  StructureDefinitionKindValue_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StructureDefinitionKindValue_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StructureDefinitionKindValue_IsValid(int value);
const StructureDefinitionKindValue StructureDefinitionKindValue_MIN = KIND_UNKNOWN;
const StructureDefinitionKindValue StructureDefinitionKindValue_MAX = KIND_LOGICAL;
const int StructureDefinitionKindValue_ARRAYSIZE = StructureDefinitionKindValue_MAX + 1;

const ::google::protobuf::EnumDescriptor* StructureDefinitionKindValue_descriptor();
inline const ::std::string& StructureDefinitionKindValue_Name(StructureDefinitionKindValue value) {
  return ::google::protobuf::internal::NameOfEnum(
    StructureDefinitionKindValue_descriptor(), value);
}
inline bool StructureDefinitionKindValue_Parse(
    const ::std::string& name, StructureDefinitionKindValue* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StructureDefinitionKindValue>(
    StructureDefinitionKindValue_descriptor(), name, value);
}
enum Requirement {
  NOT_REQUIRED = 0,
  REQUIRED_BY_FHIR = 1,
  Requirement_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Requirement_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Requirement_IsValid(int value);
const Requirement Requirement_MIN = NOT_REQUIRED;
const Requirement Requirement_MAX = REQUIRED_BY_FHIR;
const int Requirement_ARRAYSIZE = Requirement_MAX + 1;

const ::google::protobuf::EnumDescriptor* Requirement_descriptor();
inline const ::std::string& Requirement_Name(Requirement value) {
  return ::google::protobuf::internal::NameOfEnum(
    Requirement_descriptor(), value);
}
inline bool Requirement_Parse(
    const ::std::string& name, Requirement* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Requirement>(
    Requirement_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kFhirValuesetUrlFieldNumber = 180887441;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_valueset_url;
static const int kFhirReferenceTypeFieldNumber = 183546385;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  fhir_reference_type;
static const int kStructureDefinitionKindFieldNumber = 182131192;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::google::fhir::stu3::proto::StructureDefinitionKindValue, ::google::fhir::stu3::proto::StructureDefinitionKindValue_IsValid>, 14, false >
  structure_definition_kind;
static const int kMessageDescriptionFieldNumber = 190563156;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  message_description;
static const int kValueRegexFieldNumber = 204543906;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  value_regex;
static const int kFhirStructureDefinitionUrlFieldNumber = 207562726;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_structure_definition_url;
static const int kFhirProfileBaseFieldNumber = 206336851;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_profile_base;
static const int kFhirExtensionUrlFieldNumber = 177048773;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_extension_url;
static const int kFhirOriginalCodeFieldNumber = 181000551;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_original_code;
static const int kValidationRequirementFieldNumber = 162282766;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::google::fhir::stu3::proto::Requirement, ::google::fhir::stu3::proto::Requirement_IsValid>, 14, false >
  validation_requirement;
static const int kIsChoiceTypeFieldNumber = 187112991;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  is_choice_type;
static const int kFieldDescriptionFieldNumber = 190357977;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_description;
static const int kFhirSliceByFieldNumber = 211855060;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_by;
static const int kFhirSliceOfFieldNumber = 211842556;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_of;
static const int kFhirSliceValueFieldNumber = 211855323;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_slice_value;
static const int kFhirInlinedExtensionUrlFieldNumber = 206340037;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_extension_url;
static const int kFhirInlinedCodingSystemFieldNumber = 211854975;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_coding_system;
static const int kFhirInlinedCodingCodeFieldNumber = 212122564;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fhir_inlined_coding_code;
static const int kValidReferenceTypeFieldNumber = 218884094;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  valid_reference_type;
static const int kFhirOneofIsOptionalFieldNumber = 214472422;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::OneofOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  fhir_oneof_is_optional;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::google::fhir::stu3::proto::StructureDefinitionKindValue> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::fhir::stu3::proto::StructureDefinitionKindValue>() {
  return ::google::fhir::stu3::proto::StructureDefinitionKindValue_descriptor();
}
template <> struct is_proto_enum< ::google::fhir::stu3::proto::Requirement> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::fhir::stu3::proto::Requirement>() {
  return ::google::fhir::stu3::proto::Requirement_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_2fstu3_2fannotations_2eproto
