// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/uscore_codes.proto

#ifndef PROTOBUF_INCLUDED_proto_2fstu3_2fuscore_5fcodes_2eproto
#define PROTOBUF_INCLUDED_proto_2fstu3_2fuscore_5fcodes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/stu3/annotations.pb.h"
#include "proto/stu3/datatypes.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto 

namespace protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace uscore {
class UsCoreBirthSexCode;
class UsCoreBirthSexCodeDefaultTypeInternal;
extern UsCoreBirthSexCodeDefaultTypeInternal _UsCoreBirthSexCode_default_instance_;
}  // namespace uscore
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace google {
namespace protobuf {
template<> ::google::fhir::stu3::uscore::UsCoreBirthSexCode* Arena::CreateMaybeMessage<::google::fhir::stu3::uscore::UsCoreBirthSexCode>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace google {
namespace fhir {
namespace stu3 {
namespace uscore {

enum UsCoreBirthSexCode_Value {
  UsCoreBirthSexCode_Value_INVALID_UNINITIALIZED = 0,
  UsCoreBirthSexCode_Value_FEMALE = 1,
  UsCoreBirthSexCode_Value_MALE = 2,
  UsCoreBirthSexCode_Value_UNKNOWN = 3,
  UsCoreBirthSexCode_Value_UsCoreBirthSexCode_Value_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UsCoreBirthSexCode_Value_UsCoreBirthSexCode_Value_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UsCoreBirthSexCode_Value_IsValid(int value);
const UsCoreBirthSexCode_Value UsCoreBirthSexCode_Value_Value_MIN = UsCoreBirthSexCode_Value_INVALID_UNINITIALIZED;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode_Value_Value_MAX = UsCoreBirthSexCode_Value_UNKNOWN;
const int UsCoreBirthSexCode_Value_Value_ARRAYSIZE = UsCoreBirthSexCode_Value_Value_MAX + 1;

const ::google::protobuf::EnumDescriptor* UsCoreBirthSexCode_Value_descriptor();
inline const ::std::string& UsCoreBirthSexCode_Value_Name(UsCoreBirthSexCode_Value value) {
  return ::google::protobuf::internal::NameOfEnum(
    UsCoreBirthSexCode_Value_descriptor(), value);
}
inline bool UsCoreBirthSexCode_Value_Parse(
    const ::std::string& name, UsCoreBirthSexCode_Value* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UsCoreBirthSexCode_Value>(
    UsCoreBirthSexCode_Value_descriptor(), name, value);
}
// ===================================================================

class UsCoreBirthSexCode : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.fhir.stu3.uscore.UsCoreBirthSexCode) */ {
 public:
  UsCoreBirthSexCode();
  virtual ~UsCoreBirthSexCode();

  UsCoreBirthSexCode(const UsCoreBirthSexCode& from);

  inline UsCoreBirthSexCode& operator=(const UsCoreBirthSexCode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UsCoreBirthSexCode(UsCoreBirthSexCode&& from) noexcept
    : UsCoreBirthSexCode() {
    *this = ::std::move(from);
  }

  inline UsCoreBirthSexCode& operator=(UsCoreBirthSexCode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UsCoreBirthSexCode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UsCoreBirthSexCode* internal_default_instance() {
    return reinterpret_cast<const UsCoreBirthSexCode*>(
               &_UsCoreBirthSexCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UsCoreBirthSexCode* other);
  friend void swap(UsCoreBirthSexCode& a, UsCoreBirthSexCode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UsCoreBirthSexCode* New() const final {
    return CreateMaybeMessage<UsCoreBirthSexCode>(NULL);
  }

  UsCoreBirthSexCode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UsCoreBirthSexCode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UsCoreBirthSexCode& from);
  void MergeFrom(const UsCoreBirthSexCode& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UsCoreBirthSexCode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UsCoreBirthSexCode_Value Value;
  static const Value INVALID_UNINITIALIZED =
    UsCoreBirthSexCode_Value_INVALID_UNINITIALIZED;
  static const Value FEMALE =
    UsCoreBirthSexCode_Value_FEMALE;
  static const Value MALE =
    UsCoreBirthSexCode_Value_MALE;
  static const Value UNKNOWN =
    UsCoreBirthSexCode_Value_UNKNOWN;
  static inline bool Value_IsValid(int value) {
    return UsCoreBirthSexCode_Value_IsValid(value);
  }
  static const Value Value_MIN =
    UsCoreBirthSexCode_Value_Value_MIN;
  static const Value Value_MAX =
    UsCoreBirthSexCode_Value_Value_MAX;
  static const int Value_ARRAYSIZE =
    UsCoreBirthSexCode_Value_Value_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Value_descriptor() {
    return UsCoreBirthSexCode_Value_descriptor();
  }
  static inline const ::std::string& Value_Name(Value value) {
    return UsCoreBirthSexCode_Value_Name(value);
  }
  static inline bool Value_Parse(const ::std::string& name,
      Value* value) {
    return UsCoreBirthSexCode_Value_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .google.fhir.stu3.proto.Extension extension = 3;
  int extension_size() const;
  void clear_extension();
  static const int kExtensionFieldNumber = 3;
  ::google::fhir::stu3::proto::Extension* mutable_extension(int index);
  ::google::protobuf::RepeatedPtrField< ::google::fhir::stu3::proto::Extension >*
      mutable_extension();
  const ::google::fhir::stu3::proto::Extension& extension(int index) const;
  ::google::fhir::stu3::proto::Extension* add_extension();
  const ::google::protobuf::RepeatedPtrField< ::google::fhir::stu3::proto::Extension >&
      extension() const;

  // .google.fhir.stu3.proto.String id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  private:
  const ::google::fhir::stu3::proto::String& _internal_id() const;
  public:
  const ::google::fhir::stu3::proto::String& id() const;
  ::google::fhir::stu3::proto::String* release_id();
  ::google::fhir::stu3::proto::String* mutable_id();
  void set_allocated_id(::google::fhir::stu3::proto::String* id);

  // .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value value() const;
  void set_value(::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value value);

  // @@protoc_insertion_point(class_scope:google.fhir.stu3.uscore.UsCoreBirthSexCode)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::fhir::stu3::proto::Extension > extension_;
  ::google::fhir::stu3::proto::String* id_;
  int value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UsCoreBirthSexCode

// .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
inline void UsCoreBirthSexCode::clear_value() {
  value_ = 0;
}
inline ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value UsCoreBirthSexCode::value() const {
  // @@protoc_insertion_point(field_get:google.fhir.stu3.uscore.UsCoreBirthSexCode.value)
  return static_cast< ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value >(value_);
}
inline void UsCoreBirthSexCode::set_value(::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:google.fhir.stu3.uscore.UsCoreBirthSexCode.value)
}

// .google.fhir.stu3.proto.String id = 2;
inline bool UsCoreBirthSexCode::has_id() const {
  return this != internal_default_instance() && id_ != NULL;
}
inline const ::google::fhir::stu3::proto::String& UsCoreBirthSexCode::_internal_id() const {
  return *id_;
}
inline const ::google::fhir::stu3::proto::String& UsCoreBirthSexCode::id() const {
  const ::google::fhir::stu3::proto::String* p = id_;
  // @@protoc_insertion_point(field_get:google.fhir.stu3.uscore.UsCoreBirthSexCode.id)
  return p != NULL ? *p : *reinterpret_cast<const ::google::fhir::stu3::proto::String*>(
      &::google::fhir::stu3::proto::_String_default_instance_);
}
inline ::google::fhir::stu3::proto::String* UsCoreBirthSexCode::release_id() {
  // @@protoc_insertion_point(field_release:google.fhir.stu3.uscore.UsCoreBirthSexCode.id)
  
  ::google::fhir::stu3::proto::String* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::google::fhir::stu3::proto::String* UsCoreBirthSexCode::mutable_id() {
  
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::google::fhir::stu3::proto::String>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:google.fhir.stu3.uscore.UsCoreBirthSexCode.id)
  return id_;
}
inline void UsCoreBirthSexCode::set_allocated_id(::google::fhir::stu3::proto::String* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    
  } else {
    
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:google.fhir.stu3.uscore.UsCoreBirthSexCode.id)
}

// repeated .google.fhir.stu3.proto.Extension extension = 3;
inline int UsCoreBirthSexCode::extension_size() const {
  return extension_.size();
}
inline ::google::fhir::stu3::proto::Extension* UsCoreBirthSexCode::mutable_extension(int index) {
  // @@protoc_insertion_point(field_mutable:google.fhir.stu3.uscore.UsCoreBirthSexCode.extension)
  return extension_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::google::fhir::stu3::proto::Extension >*
UsCoreBirthSexCode::mutable_extension() {
  // @@protoc_insertion_point(field_mutable_list:google.fhir.stu3.uscore.UsCoreBirthSexCode.extension)
  return &extension_;
}
inline const ::google::fhir::stu3::proto::Extension& UsCoreBirthSexCode::extension(int index) const {
  // @@protoc_insertion_point(field_get:google.fhir.stu3.uscore.UsCoreBirthSexCode.extension)
  return extension_.Get(index);
}
inline ::google::fhir::stu3::proto::Extension* UsCoreBirthSexCode::add_extension() {
  // @@protoc_insertion_point(field_add:google.fhir.stu3.uscore.UsCoreBirthSexCode.extension)
  return extension_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::fhir::stu3::proto::Extension >&
UsCoreBirthSexCode::extension() const {
  // @@protoc_insertion_point(field_list:google.fhir.stu3.uscore.UsCoreBirthSexCode.extension)
  return extension_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace uscore
}  // namespace stu3
}  // namespace fhir
}  // namespace google

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value>() {
  return ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_2fstu3_2fuscore_5fcodes_2eproto
