// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/uscore_codes.proto

#include "proto/stu3/uscore_codes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_proto_2fstu3_2fdatatypes_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fdatatypes_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Address;
}  // namespace protobuf_proto_2fstu3_2fdatatypes_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace uscore {
class UsCoreBirthSexCodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UsCoreBirthSexCode>
      _instance;
} _UsCoreBirthSexCode_default_instance_;
}  // namespace uscore
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto {
static void InitDefaultsUsCoreBirthSexCode() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::fhir::stu3::uscore::_UsCoreBirthSexCode_default_instance_;
    new (ptr) ::google::fhir::stu3::uscore::UsCoreBirthSexCode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::fhir::stu3::uscore::UsCoreBirthSexCode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_UsCoreBirthSexCode =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsUsCoreBirthSexCode}, {
      &protobuf_proto_2fstu3_2fdatatypes_2eproto::scc_info_Address.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_UsCoreBirthSexCode.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::uscore::UsCoreBirthSexCode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::uscore::UsCoreBirthSexCode, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::uscore::UsCoreBirthSexCode, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::uscore::UsCoreBirthSexCode, extension_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::fhir::stu3::uscore::UsCoreBirthSexCode)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::fhir::stu3::uscore::_UsCoreBirthSexCode_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "proto/stu3/uscore_codes.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035proto/stu3/uscore_codes.proto\022\027google."
      "fhir.stu3.uscore\032\034proto/stu3/annotations"
      ".proto\032\032proto/stu3/datatypes.proto\"\337\002\n\022U"
      "sCoreBirthSexCode\022@\n\005value\030\001 \001(\01621.googl"
      "e.fhir.stu3.uscore.UsCoreBirthSexCode.Va"
      "lue\022*\n\002id\030\002 \001(\0132\036.google.fhir.stu3.proto"
      ".String\0224\n\textension\030\003 \003(\0132!.google.fhir"
      ".stu3.proto.Extension\"b\n\005Value\022\031\n\025INVALI"
      "D_UNINITIALIZED\020\000\022\023\n\006FEMALE\020\001\032\007\272\226\273\262\005\001F\022\021"
      "\n\004MALE\020\002\032\007\272\226\273\262\005\001M\022\026\n\007UNKNOWN\020\003\032\t\272\226\273\262\005\003UN"
      "K:A\300\237\343\266\005\001\212\371\203\262\0055http://hl7.org/fhir/us/co"
      "re/ValueSet/us-core-birthsexB\037\n\033com.goog"
      "le.fhir.stu3.uscoreP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 509);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/stu3/uscore_codes.proto", &protobuf_RegisterTypes);
  ::protobuf_proto_2fstu3_2fannotations_2eproto::AddDescriptors();
  ::protobuf_proto_2fstu3_2fdatatypes_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace uscore {
const ::google::protobuf::EnumDescriptor* UsCoreBirthSexCode_Value_descriptor() {
  protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::file_level_enum_descriptors[0];
}
bool UsCoreBirthSexCode_Value_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::INVALID_UNINITIALIZED;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::FEMALE;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::MALE;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::UNKNOWN;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::Value_MIN;
const UsCoreBirthSexCode_Value UsCoreBirthSexCode::Value_MAX;
const int UsCoreBirthSexCode::Value_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void UsCoreBirthSexCode::InitAsDefaultInstance() {
  ::google::fhir::stu3::uscore::_UsCoreBirthSexCode_default_instance_._instance.get_mutable()->id_ = const_cast< ::google::fhir::stu3::proto::String*>(
      ::google::fhir::stu3::proto::String::internal_default_instance());
}
void UsCoreBirthSexCode::clear_id() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) {
    delete id_;
  }
  id_ = NULL;
}
void UsCoreBirthSexCode::clear_extension() {
  extension_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UsCoreBirthSexCode::kValueFieldNumber;
const int UsCoreBirthSexCode::kIdFieldNumber;
const int UsCoreBirthSexCode::kExtensionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UsCoreBirthSexCode::UsCoreBirthSexCode()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::scc_info_UsCoreBirthSexCode.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.fhir.stu3.uscore.UsCoreBirthSexCode)
}
UsCoreBirthSexCode::UsCoreBirthSexCode(const UsCoreBirthSexCode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      extension_(from.extension_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_id()) {
    id_ = new ::google::fhir::stu3::proto::String(*from.id_);
  } else {
    id_ = NULL;
  }
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:google.fhir.stu3.uscore.UsCoreBirthSexCode)
}

void UsCoreBirthSexCode::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_));
}

UsCoreBirthSexCode::~UsCoreBirthSexCode() {
  // @@protoc_insertion_point(destructor:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  SharedDtor();
}

void UsCoreBirthSexCode::SharedDtor() {
  if (this != internal_default_instance()) delete id_;
}

void UsCoreBirthSexCode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UsCoreBirthSexCode::descriptor() {
  ::protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UsCoreBirthSexCode& UsCoreBirthSexCode::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::scc_info_UsCoreBirthSexCode.base);
  return *internal_default_instance();
}


void UsCoreBirthSexCode::Clear() {
// @@protoc_insertion_point(message_clear_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  extension_.Clear();
  if (GetArenaNoVirtual() == NULL && id_ != NULL) {
    delete id_;
  }
  id_ = NULL;
  value_ = 0;
  _internal_metadata_.Clear();
}

bool UsCoreBirthSexCode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_value(static_cast< ::google::fhir::stu3::uscore::UsCoreBirthSexCode_Value >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.fhir.stu3.proto.String id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.fhir.stu3.proto.Extension extension = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_extension()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  return false;
#undef DO_
}

void UsCoreBirthSexCode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->value(), output);
  }

  // .google.fhir.stu3.proto.String id = 2;
  if (this->has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_id(), output);
  }

  // repeated .google.fhir.stu3.proto.Extension extension = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->extension(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.fhir.stu3.uscore.UsCoreBirthSexCode)
}

::google::protobuf::uint8* UsCoreBirthSexCode::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->value(), target);
  }

  // .google.fhir.stu3.proto.String id = 2;
  if (this->has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_id(), deterministic, target);
  }

  // repeated .google.fhir.stu3.proto.Extension extension = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->extension(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  return target;
}

size_t UsCoreBirthSexCode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.fhir.stu3.proto.Extension extension = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->extension_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->extension(static_cast<int>(i)));
    }
  }

  // .google.fhir.stu3.proto.String id = 2;
  if (this->has_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *id_);
  }

  // .google.fhir.stu3.uscore.UsCoreBirthSexCode.Value value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UsCoreBirthSexCode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  GOOGLE_DCHECK_NE(&from, this);
  const UsCoreBirthSexCode* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UsCoreBirthSexCode>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.fhir.stu3.uscore.UsCoreBirthSexCode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.fhir.stu3.uscore.UsCoreBirthSexCode)
    MergeFrom(*source);
  }
}

void UsCoreBirthSexCode::MergeFrom(const UsCoreBirthSexCode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  extension_.MergeFrom(from.extension_);
  if (from.has_id()) {
    mutable_id()->::google::fhir::stu3::proto::String::MergeFrom(from.id());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void UsCoreBirthSexCode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UsCoreBirthSexCode::CopyFrom(const UsCoreBirthSexCode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.fhir.stu3.uscore.UsCoreBirthSexCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UsCoreBirthSexCode::IsInitialized() const {
  return true;
}

void UsCoreBirthSexCode::Swap(UsCoreBirthSexCode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UsCoreBirthSexCode::InternalSwap(UsCoreBirthSexCode* other) {
  using std::swap;
  CastToBase(&extension_)->InternalSwap(CastToBase(&other->extension_));
  swap(id_, other->id_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UsCoreBirthSexCode::GetMetadata() const {
  protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fuscore_5fcodes_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace uscore
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::fhir::stu3::uscore::UsCoreBirthSexCode* Arena::CreateMaybeMessage< ::google::fhir::stu3::uscore::UsCoreBirthSexCode >(Arena* arena) {
  return Arena::CreateInternal< ::google::fhir::stu3::uscore::UsCoreBirthSexCode >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
