// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/version_config.proto

#include "proto/stu3/version_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_proto_2fstu3_2fversion_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fversion_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ResourceConfig_TimestampOverride;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fversion_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ResourceConfig;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fstu3_2fversion_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_VersionConfig_ResourceConfigEntry_DoNotUse;
}  // namespace protobuf_proto_2fstu3_2fversion_5fconfig_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace proto {
class ResourceConfig_TimestampOverrideDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResourceConfig_TimestampOverride>
      _instance;
} _ResourceConfig_TimestampOverride_default_instance_;
class ResourceConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResourceConfig>
      _instance;
} _ResourceConfig_default_instance_;
class VersionConfig_ResourceConfigEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VersionConfig_ResourceConfigEntry_DoNotUse>
      _instance;
} _VersionConfig_ResourceConfigEntry_DoNotUse_default_instance_;
class VersionConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VersionConfig>
      _instance;
} _VersionConfig_default_instance_;
}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace protobuf_proto_2fstu3_2fversion_5fconfig_2eproto {
static void InitDefaultsResourceConfig_TimestampOverride() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::fhir::stu3::proto::_ResourceConfig_TimestampOverride_default_instance_;
    new (ptr) ::google::fhir::stu3::proto::ResourceConfig_TimestampOverride();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::fhir::stu3::proto::ResourceConfig_TimestampOverride::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResourceConfig_TimestampOverride =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResourceConfig_TimestampOverride}, {}};

static void InitDefaultsResourceConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::fhir::stu3::proto::_ResourceConfig_default_instance_;
    new (ptr) ::google::fhir::stu3::proto::ResourceConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::fhir::stu3::proto::ResourceConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ResourceConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsResourceConfig}, {
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig_TimestampOverride.base,}};

static void InitDefaultsVersionConfig_ResourceConfigEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::fhir::stu3::proto::_VersionConfig_ResourceConfigEntry_DoNotUse_default_instance_;
    new (ptr) ::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse();
  }
  ::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_VersionConfig_ResourceConfigEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsVersionConfig_ResourceConfigEntry_DoNotUse}, {
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig.base,}};

static void InitDefaultsVersionConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::fhir::stu3::proto::_VersionConfig_default_instance_;
    new (ptr) ::google::fhir::stu3::proto::VersionConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::fhir::stu3::proto::VersionConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_VersionConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsVersionConfig}, {
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_VersionConfig_ResourceConfigEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ResourceConfig_TimestampOverride.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResourceConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VersionConfig_ResourceConfigEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VersionConfig.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig_TimestampOverride, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig_TimestampOverride, timestamp_field_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig_TimestampOverride, resource_field_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig, default_timestamp_fields_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::ResourceConfig, timestamp_override_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::fhir::stu3::proto::VersionConfig, resource_config_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::fhir::stu3::proto::ResourceConfig_TimestampOverride)},
  { 7, -1, sizeof(::google::fhir::stu3::proto::ResourceConfig)},
  { 14, 21, sizeof(::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse)},
  { 23, -1, sizeof(::google::fhir::stu3::proto::VersionConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::fhir::stu3::proto::_ResourceConfig_TimestampOverride_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::fhir::stu3::proto::_ResourceConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::fhir::stu3::proto::_VersionConfig_ResourceConfigEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::fhir::stu3::proto::_VersionConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "proto/stu3/version_config.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\037proto/stu3/version_config.proto\022\026googl"
      "e.fhir.stu3.proto\"\340\001\n\016ResourceConfig\022 \n\030"
      "default_timestamp_fields\030\001 \003(\t\022T\n\022timest"
      "amp_override\030\005 \003(\01328.google.fhir.stu3.pr"
      "oto.ResourceConfig.TimestampOverride\032D\n\021"
      "TimestampOverride\022\027\n\017timestamp_field\030\001 \001"
      "(\t\022\026\n\016resource_field\030\002 \003(\tJ\004\010\002\020\003J\004\010\003\020\004J\004"
      "\010\004\020\005\"\302\001\n\rVersionConfig\022R\n\017resource_confi"
      "g\030\001 \003(\01329.google.fhir.stu3.proto.Version"
      "Config.ResourceConfigEntry\032]\n\023ResourceCo"
      "nfigEntry\022\013\n\003key\030\001 \001(\t\0225\n\005value\030\002 \001(\0132&."
      "google.fhir.stu3.proto.ResourceConfig:\0028"
      "\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 489);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/stu3/version_config.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fstu3_2fversion_5fconfig_2eproto
namespace google {
namespace fhir {
namespace stu3 {
namespace proto {

// ===================================================================

void ResourceConfig_TimestampOverride::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResourceConfig_TimestampOverride::kTimestampFieldFieldNumber;
const int ResourceConfig_TimestampOverride::kResourceFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResourceConfig_TimestampOverride::ResourceConfig_TimestampOverride()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig_TimestampOverride.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
}
ResourceConfig_TimestampOverride::ResourceConfig_TimestampOverride(const ResourceConfig_TimestampOverride& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      resource_field_(from.resource_field_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timestamp_field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.timestamp_field().size() > 0) {
    timestamp_field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.timestamp_field_);
  }
  // @@protoc_insertion_point(copy_constructor:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
}

void ResourceConfig_TimestampOverride::SharedCtor() {
  timestamp_field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ResourceConfig_TimestampOverride::~ResourceConfig_TimestampOverride() {
  // @@protoc_insertion_point(destructor:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  SharedDtor();
}

void ResourceConfig_TimestampOverride::SharedDtor() {
  timestamp_field_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ResourceConfig_TimestampOverride::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResourceConfig_TimestampOverride::descriptor() {
  ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResourceConfig_TimestampOverride& ResourceConfig_TimestampOverride::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig_TimestampOverride.base);
  return *internal_default_instance();
}


void ResourceConfig_TimestampOverride::Clear() {
// @@protoc_insertion_point(message_clear_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  resource_field_.Clear();
  timestamp_field_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ResourceConfig_TimestampOverride::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string timestamp_field = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_timestamp_field()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->timestamp_field().data(), static_cast<int>(this->timestamp_field().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.timestamp_field"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string resource_field = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_resource_field()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->resource_field(this->resource_field_size() - 1).data(),
            static_cast<int>(this->resource_field(this->resource_field_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.resource_field"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  return false;
#undef DO_
}

void ResourceConfig_TimestampOverride::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string timestamp_field = 1;
  if (this->timestamp_field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->timestamp_field().data(), static_cast<int>(this->timestamp_field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.timestamp_field");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->timestamp_field(), output);
  }

  // repeated string resource_field = 2;
  for (int i = 0, n = this->resource_field_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resource_field(i).data(), static_cast<int>(this->resource_field(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.resource_field");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->resource_field(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
}

::google::protobuf::uint8* ResourceConfig_TimestampOverride::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string timestamp_field = 1;
  if (this->timestamp_field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->timestamp_field().data(), static_cast<int>(this->timestamp_field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.timestamp_field");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->timestamp_field(), target);
  }

  // repeated string resource_field = 2;
  for (int i = 0, n = this->resource_field_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resource_field(i).data(), static_cast<int>(this->resource_field(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.TimestampOverride.resource_field");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->resource_field(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  return target;
}

size_t ResourceConfig_TimestampOverride::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string resource_field = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->resource_field_size());
  for (int i = 0, n = this->resource_field_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->resource_field(i));
  }

  // string timestamp_field = 1;
  if (this->timestamp_field().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->timestamp_field());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResourceConfig_TimestampOverride::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  GOOGLE_DCHECK_NE(&from, this);
  const ResourceConfig_TimestampOverride* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResourceConfig_TimestampOverride>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
    MergeFrom(*source);
  }
}

void ResourceConfig_TimestampOverride::MergeFrom(const ResourceConfig_TimestampOverride& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  resource_field_.MergeFrom(from.resource_field_);
  if (from.timestamp_field().size() > 0) {

    timestamp_field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.timestamp_field_);
  }
}

void ResourceConfig_TimestampOverride::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResourceConfig_TimestampOverride::CopyFrom(const ResourceConfig_TimestampOverride& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceConfig_TimestampOverride::IsInitialized() const {
  return true;
}

void ResourceConfig_TimestampOverride::Swap(ResourceConfig_TimestampOverride* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResourceConfig_TimestampOverride::InternalSwap(ResourceConfig_TimestampOverride* other) {
  using std::swap;
  resource_field_.InternalSwap(CastToBase(&other->resource_field_));
  timestamp_field_.Swap(&other->timestamp_field_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResourceConfig_TimestampOverride::GetMetadata() const {
  protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResourceConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResourceConfig::kDefaultTimestampFieldsFieldNumber;
const int ResourceConfig::kTimestampOverrideFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResourceConfig::ResourceConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.fhir.stu3.proto.ResourceConfig)
}
ResourceConfig::ResourceConfig(const ResourceConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      default_timestamp_fields_(from.default_timestamp_fields_),
      timestamp_override_(from.timestamp_override_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.fhir.stu3.proto.ResourceConfig)
}

void ResourceConfig::SharedCtor() {
}

ResourceConfig::~ResourceConfig() {
  // @@protoc_insertion_point(destructor:google.fhir.stu3.proto.ResourceConfig)
  SharedDtor();
}

void ResourceConfig::SharedDtor() {
}

void ResourceConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResourceConfig::descriptor() {
  ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResourceConfig& ResourceConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_ResourceConfig.base);
  return *internal_default_instance();
}


void ResourceConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:google.fhir.stu3.proto.ResourceConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  default_timestamp_fields_.Clear();
  timestamp_override_.Clear();
  _internal_metadata_.Clear();
}

bool ResourceConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.fhir.stu3.proto.ResourceConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string default_timestamp_fields = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_default_timestamp_fields()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->default_timestamp_fields(this->default_timestamp_fields_size() - 1).data(),
            static_cast<int>(this->default_timestamp_fields(this->default_timestamp_fields_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.fhir.stu3.proto.ResourceConfig.default_timestamp_fields"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.fhir.stu3.proto.ResourceConfig.TimestampOverride timestamp_override = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_timestamp_override()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.fhir.stu3.proto.ResourceConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.fhir.stu3.proto.ResourceConfig)
  return false;
#undef DO_
}

void ResourceConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.fhir.stu3.proto.ResourceConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string default_timestamp_fields = 1;
  for (int i = 0, n = this->default_timestamp_fields_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->default_timestamp_fields(i).data(), static_cast<int>(this->default_timestamp_fields(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.default_timestamp_fields");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->default_timestamp_fields(i), output);
  }

  // repeated .google.fhir.stu3.proto.ResourceConfig.TimestampOverride timestamp_override = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->timestamp_override_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->timestamp_override(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.fhir.stu3.proto.ResourceConfig)
}

::google::protobuf::uint8* ResourceConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.fhir.stu3.proto.ResourceConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string default_timestamp_fields = 1;
  for (int i = 0, n = this->default_timestamp_fields_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->default_timestamp_fields(i).data(), static_cast<int>(this->default_timestamp_fields(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.fhir.stu3.proto.ResourceConfig.default_timestamp_fields");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->default_timestamp_fields(i), target);
  }

  // repeated .google.fhir.stu3.proto.ResourceConfig.TimestampOverride timestamp_override = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->timestamp_override_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->timestamp_override(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.fhir.stu3.proto.ResourceConfig)
  return target;
}

size_t ResourceConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.fhir.stu3.proto.ResourceConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string default_timestamp_fields = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->default_timestamp_fields_size());
  for (int i = 0, n = this->default_timestamp_fields_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->default_timestamp_fields(i));
  }

  // repeated .google.fhir.stu3.proto.ResourceConfig.TimestampOverride timestamp_override = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->timestamp_override_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->timestamp_override(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResourceConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.fhir.stu3.proto.ResourceConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const ResourceConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResourceConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.fhir.stu3.proto.ResourceConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.fhir.stu3.proto.ResourceConfig)
    MergeFrom(*source);
  }
}

void ResourceConfig::MergeFrom(const ResourceConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.fhir.stu3.proto.ResourceConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  default_timestamp_fields_.MergeFrom(from.default_timestamp_fields_);
  timestamp_override_.MergeFrom(from.timestamp_override_);
}

void ResourceConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.fhir.stu3.proto.ResourceConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResourceConfig::CopyFrom(const ResourceConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.fhir.stu3.proto.ResourceConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceConfig::IsInitialized() const {
  return true;
}

void ResourceConfig::Swap(ResourceConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResourceConfig::InternalSwap(ResourceConfig* other) {
  using std::swap;
  default_timestamp_fields_.InternalSwap(CastToBase(&other->default_timestamp_fields_));
  CastToBase(&timestamp_override_)->InternalSwap(CastToBase(&other->timestamp_override_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResourceConfig::GetMetadata() const {
  protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

VersionConfig_ResourceConfigEntry_DoNotUse::VersionConfig_ResourceConfigEntry_DoNotUse() {}
VersionConfig_ResourceConfigEntry_DoNotUse::VersionConfig_ResourceConfigEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void VersionConfig_ResourceConfigEntry_DoNotUse::MergeFrom(const VersionConfig_ResourceConfigEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata VersionConfig_ResourceConfigEntry_DoNotUse::GetMetadata() const {
  ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[2];
}
void VersionConfig_ResourceConfigEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void VersionConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VersionConfig::kResourceConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VersionConfig::VersionConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_VersionConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.fhir.stu3.proto.VersionConfig)
}
VersionConfig::VersionConfig(const VersionConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  resource_config_.MergeFrom(from.resource_config_);
  // @@protoc_insertion_point(copy_constructor:google.fhir.stu3.proto.VersionConfig)
}

void VersionConfig::SharedCtor() {
}

VersionConfig::~VersionConfig() {
  // @@protoc_insertion_point(destructor:google.fhir.stu3.proto.VersionConfig)
  SharedDtor();
}

void VersionConfig::SharedDtor() {
}

void VersionConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VersionConfig::descriptor() {
  ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VersionConfig& VersionConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::scc_info_VersionConfig.base);
  return *internal_default_instance();
}


void VersionConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:google.fhir.stu3.proto.VersionConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  resource_config_.Clear();
  _internal_metadata_.Clear();
}

bool VersionConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.fhir.stu3.proto.VersionConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, .google.fhir.stu3.proto.ResourceConfig> resource_config = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          VersionConfig_ResourceConfigEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              VersionConfig_ResourceConfigEntry_DoNotUse,
              ::std::string, ::google::fhir::stu3::proto::ResourceConfig,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig > > parser(&resource_config_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.fhir.stu3.proto.VersionConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.fhir.stu3.proto.VersionConfig)
  return false;
#undef DO_
}

void VersionConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.fhir.stu3.proto.VersionConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .google.fhir.stu3.proto.ResourceConfig> resource_config = 1;
  if (!this->resource_config().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->resource_config().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->resource_config().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_iterator
          it = this->resource_config().begin();
          it != this->resource_config().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<VersionConfig_ResourceConfigEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(resource_config_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<VersionConfig_ResourceConfigEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_iterator
          it = this->resource_config().begin();
          it != this->resource_config().end(); ++it) {
        entry.reset(resource_config_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.fhir.stu3.proto.VersionConfig)
}

::google::protobuf::uint8* VersionConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.fhir.stu3.proto.VersionConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .google.fhir.stu3.proto.ResourceConfig> resource_config = 1;
  if (!this->resource_config().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry.key");
      }
    };

    if (deterministic &&
        this->resource_config().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->resource_config().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_iterator
          it = this->resource_config().begin();
          it != this->resource_config().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<VersionConfig_ResourceConfigEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(resource_config_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<VersionConfig_ResourceConfigEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_iterator
          it = this->resource_config().begin();
          it != this->resource_config().end(); ++it) {
        entry.reset(resource_config_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.fhir.stu3.proto.VersionConfig)
  return target;
}

size_t VersionConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.fhir.stu3.proto.VersionConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, .google.fhir.stu3.proto.ResourceConfig> resource_config = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->resource_config_size());
  {
    ::std::unique_ptr<VersionConfig_ResourceConfigEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::google::fhir::stu3::proto::ResourceConfig >::const_iterator
        it = this->resource_config().begin();
        it != this->resource_config().end(); ++it) {
      entry.reset(resource_config_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VersionConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.fhir.stu3.proto.VersionConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const VersionConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VersionConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.fhir.stu3.proto.VersionConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.fhir.stu3.proto.VersionConfig)
    MergeFrom(*source);
  }
}

void VersionConfig::MergeFrom(const VersionConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.fhir.stu3.proto.VersionConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  resource_config_.MergeFrom(from.resource_config_);
}

void VersionConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.fhir.stu3.proto.VersionConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VersionConfig::CopyFrom(const VersionConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.fhir.stu3.proto.VersionConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VersionConfig::IsInitialized() const {
  return true;
}

void VersionConfig::Swap(VersionConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VersionConfig::InternalSwap(VersionConfig* other) {
  using std::swap;
  resource_config_.Swap(&other->resource_config_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VersionConfig::GetMetadata() const {
  protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fstu3_2fversion_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace stu3
}  // namespace fhir
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::fhir::stu3::proto::ResourceConfig_TimestampOverride* Arena::CreateMaybeMessage< ::google::fhir::stu3::proto::ResourceConfig_TimestampOverride >(Arena* arena) {
  return Arena::CreateInternal< ::google::fhir::stu3::proto::ResourceConfig_TimestampOverride >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::fhir::stu3::proto::ResourceConfig* Arena::CreateMaybeMessage< ::google::fhir::stu3::proto::ResourceConfig >(Arena* arena) {
  return Arena::CreateInternal< ::google::fhir::stu3::proto::ResourceConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse* Arena::CreateMaybeMessage< ::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::google::fhir::stu3::proto::VersionConfig_ResourceConfigEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::fhir::stu3::proto::VersionConfig* Arena::CreateMaybeMessage< ::google::fhir::stu3::proto::VersionConfig >(Arena* arena) {
  return Arena::CreateInternal< ::google::fhir::stu3::proto::VersionConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
