# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/stu3/version_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/stu3/version_config.proto',
  package='google.fhir.stu3.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fproto/stu3/version_config.proto\x12\x16google.fhir.stu3.proto\"\xe0\x01\n\x0eResourceConfig\x12 \n\x18\x64\x65\x66\x61ult_timestamp_fields\x18\x01 \x03(\t\x12T\n\x12timestamp_override\x18\x05 \x03(\x0b\x32\x38.google.fhir.stu3.proto.ResourceConfig.TimestampOverride\x1a\x44\n\x11TimestampOverride\x12\x17\n\x0ftimestamp_field\x18\x01 \x01(\t\x12\x16\n\x0eresource_field\x18\x02 \x03(\tJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"\xc2\x01\n\rVersionConfig\x12R\n\x0fresource_config\x18\x01 \x03(\x0b\x32\x39.google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry\x1a]\n\x13ResourceConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.google.fhir.stu3.proto.ResourceConfig:\x02\x38\x01\x62\x06proto3')
)




_RESOURCECONFIG_TIMESTAMPOVERRIDE = _descriptor.Descriptor(
  name='TimestampOverride',
  full_name='google.fhir.stu3.proto.ResourceConfig.TimestampOverride',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_field', full_name='google.fhir.stu3.proto.ResourceConfig.TimestampOverride.timestamp_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource_field', full_name='google.fhir.stu3.proto.ResourceConfig.TimestampOverride.resource_field', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=266,
)

_RESOURCECONFIG = _descriptor.Descriptor(
  name='ResourceConfig',
  full_name='google.fhir.stu3.proto.ResourceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default_timestamp_fields', full_name='google.fhir.stu3.proto.ResourceConfig.default_timestamp_fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_override', full_name='google.fhir.stu3.proto.ResourceConfig.timestamp_override', index=1,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESOURCECONFIG_TIMESTAMPOVERRIDE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=284,
)


_VERSIONCONFIG_RESOURCECONFIGENTRY = _descriptor.Descriptor(
  name='ResourceConfigEntry',
  full_name='google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=481,
)

_VERSIONCONFIG = _descriptor.Descriptor(
  name='VersionConfig',
  full_name='google.fhir.stu3.proto.VersionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_config', full_name='google.fhir.stu3.proto.VersionConfig.resource_config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VERSIONCONFIG_RESOURCECONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=481,
)

_RESOURCECONFIG_TIMESTAMPOVERRIDE.containing_type = _RESOURCECONFIG
_RESOURCECONFIG.fields_by_name['timestamp_override'].message_type = _RESOURCECONFIG_TIMESTAMPOVERRIDE
_VERSIONCONFIG_RESOURCECONFIGENTRY.fields_by_name['value'].message_type = _RESOURCECONFIG
_VERSIONCONFIG_RESOURCECONFIGENTRY.containing_type = _VERSIONCONFIG
_VERSIONCONFIG.fields_by_name['resource_config'].message_type = _VERSIONCONFIG_RESOURCECONFIGENTRY
DESCRIPTOR.message_types_by_name['ResourceConfig'] = _RESOURCECONFIG
DESCRIPTOR.message_types_by_name['VersionConfig'] = _VERSIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceConfig = _reflection.GeneratedProtocolMessageType('ResourceConfig', (_message.Message,), dict(

  TimestampOverride = _reflection.GeneratedProtocolMessageType('TimestampOverride', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCECONFIG_TIMESTAMPOVERRIDE,
    __module__ = 'proto.stu3.version_config_pb2'
    # @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.ResourceConfig.TimestampOverride)
    ))
  ,
  DESCRIPTOR = _RESOURCECONFIG,
  __module__ = 'proto.stu3.version_config_pb2'
  # @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.ResourceConfig)
  ))
_sym_db.RegisterMessage(ResourceConfig)
_sym_db.RegisterMessage(ResourceConfig.TimestampOverride)

VersionConfig = _reflection.GeneratedProtocolMessageType('VersionConfig', (_message.Message,), dict(

  ResourceConfigEntry = _reflection.GeneratedProtocolMessageType('ResourceConfigEntry', (_message.Message,), dict(
    DESCRIPTOR = _VERSIONCONFIG_RESOURCECONFIGENTRY,
    __module__ = 'proto.stu3.version_config_pb2'
    # @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.VersionConfig.ResourceConfigEntry)
    ))
  ,
  DESCRIPTOR = _VERSIONCONFIG,
  __module__ = 'proto.stu3.version_config_pb2'
  # @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.VersionConfig)
  ))
_sym_db.RegisterMessage(VersionConfig)
_sym_db.RegisterMessage(VersionConfig.ResourceConfigEntry)


_VERSIONCONFIG_RESOURCECONFIGENTRY._options = None
# @@protoc_insertion_point(module_scope)
